blog/config/routes.rb
Rails.application.routes.draw do
  resources :animes do
    resources :comments
    resources :episodes
  end
  resources :secondseasons do
    resources :posts
    resources :second_season_episodes
  end
  resources :mangas do
    resources :chapters
    resources :views
  end
  get 'home/index'

  root 'home#index'

end

blog/app/models/anime.rb
class Anime < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
  length: { minimum: 4 }
  has_many :episodes, dependent: :destroy
  validates :title, presence: true,
  length: { minimum: 4 }
end

blog/app/models/chapter.rb
class Chapter < ActiveRecord::Base
  belongs_to :manga
end

blog/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :anime
end

blog/app/models/episode.rb
class Episode < ActiveRecord::Base
  belongs_to :anime
end

blog/app/models/manga.rb
class Manga < ActiveRecord::Base
  has_many :chapters, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 5 }
  has_many :views, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 5 }
end

blog/app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :secondseason
end

blog/app/models/second_season_episode.rb
class SecondSeasonEpisode < ActiveRecord::Base
  belongs_to :secondseason
end

blog/app/models/secondseason.rb
class Secondseason < ActiveRecord::Base
  has_many :posts, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 5 }
  has_many :second_season_episodes
  validates :title, presence: true,
                    length: { minimum: 5 }
end

blog/app/models/view.rb
class View < ActiveRecord::Base
  belongs_to :manga
end

blog/app/controllers/animes_controller.rb
class AnimesController < ApplicationController
  def destroy
    @anime = Anime.find(params[:id])
    @anime.destroy

    redirect_to animes_path
  end
  def update
    @anime = Anime.find(params[:id])

    if @anime.update(anime_params)
      redirect_to @anime
    else
      render 'edit'
    end
  end
  def edit
    @anime = Anime.find(params[:id])
  end
  def index
    @animes = Anime.all
  end
  def show
    @anime = Anime.find(params[:id])
  end
  def new
    @anime = Anime.new
  end
  def create
    @anime = Anime.new(anime_params)

    if @anime.save
      redirect_to @anime
    else
      render 'new'
    end
  end
  private
  def anime_params
    params.require(:anime).permit(:title, :text)
  end
end

blog/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

blog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def create
    @secondseason = Secondseason.find(params[:secondseason_id])
    @post = @secondseason.posts.create(post_params)
    redirect_to secondseason_path(@secondseason)
  end

  def destroy
    @secondseason = Secondseason.find(params[:secondseason_id])
    @post = @secondseason.posts.find(params[:id])
    @post.destroy
    redirect_to secondseason_path(@secondseason)
  end

  private
    def post_params
      params.require(:post).permit(:commenter, :body)
    end
end

blog/app/controllers/views_controller.rb
class ViewsController < ApplicationController
  def create
    @manga = Manga.find(params[:manga_id])
    @view = @manga.views.create(view_params)
    redirect_to manga_path(@manga)
  end

  def destroy
    @manga = Manga.find(params[:manga_id])
    @view = @manga.views.find(params[:id])
    @view.destroy
    redirect_to manga_path(@manga)
  end

  private
    def view_params
      params.require(:view).permit(:commenter, :body)
    end
end

blog/app/helpers/anime_helper.rb
module AnimeHelper
end

blog/app/helpers/animes_helper.rb
module AnimesHelper
end

blog/app/helpers/application_helper.rb
module ApplicationHelper
end

blog/app/helpers/chapters_helper.rb
module ChaptersHelper
end

blog/app/helpers/comments_helper.rb
module CommentsHelper
end

blog/app/helpers/episodes_helper.rb
module EpisodesHelper
end

blog/app/helpers/home_helper.rb
module HomeHelper
end

blog/app/helpers/mangas_helper.rb
module MangasHelper
end

blog/app/helpers/posts_helper.rb
module PostsHelper
end

blog/app/helpers/secondseasons_helper.rb
module SecondseasonsHelper
end

blog/app/helpers/views_helper.rb
module ViewsHelper
end

blog/app/views/animes/_form.html.erb
<%= form_for @anime do |f| %>
<% if @anime.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@anime.errors.count, "error") %> prohibited
    this anime from being saved:</h2>
    <ul>
      <% @anime.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>
  <% end %>

blog/app/views/animes/edit.html.erb
<h1>Editing anime</h1>

<%= render 'form' %>

<%= link_to 'Back', animes_path %>

blog/app/views/animes/index.html.erb
<h1>Listing Animes</h1>

<%= link_to 'New Anime', new_anime_path %>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="3"></th>
  </tr>

  <% @animes.each do |anime| %>
  <tr>
    <td><%= anime.title %></td>
    <td><%= anime.text %></td>
    <td><%= link_to 'Show', anime_path(anime) %></td>
    <td><%= link_to 'Edit', edit_anime_path(anime) %></td>
    <td><%= link_to 'Destroy', anime_path(anime),
    method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
  <% end %>
</table>

<%= link_to 'Home', controller: 'home' %>

blog/app/views/animes/new.html.erb
<h1>New Anime</h1>

<%= render 'form' %>

<%= link_to 'Back', animes_path %>

blog/app/views/animes/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @anime.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @anime.text %>
</p>

<h2>Episodes</h2>
<%= render @anime.episodes %>

<h2>Add a episode:</h2>
<%= render "episodes/form" %>

<h2>Comments</h2>
<%= render @anime.comments %>

<h2>Add a comment:</h2>
<%= render "comments/form" %>

<%= link_to 'Edit Anime', edit_anime_path(@anime) %> |
<%= link_to 'Back to Animes', animes_path %>