blog/config/routes.rb
Rails.application.routes.draw do
  resources :animes do
    resources :comments
    resources :episodes
  end
  resources :secondseasons do
    resources :posts
    resources :second_season_episodes
  end
  resources :mangas do
    resources :chapters
    resources :views
  end
  get 'home/index'

  root 'home#index'

end

blog/app/models/anime.rb
class Anime < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
  length: { minimum: 4 }
  has_many :episodes, dependent: :destroy
  validates :title, presence: true,
  length: { minimum: 4 }
end

blog/app/models/chapter.rb
class Chapter < ActiveRecord::Base
  belongs_to :manga
end

blog/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :anime
end

blog/app/models/episode.rb
class Episode < ActiveRecord::Base
  belongs_to :anime
end

blog/app/models/manga.rb
class Manga < ActiveRecord::Base
  has_many :chapters, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 5 }
  has_many :views, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 5 }
end

blog/app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :secondseason
end

blog/app/models/secondseason.rb
class Secondseason < ActiveRecord::Base
  has_many :posts, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 5 }
  has_many :second_season_episodes
  validates :title, presence: true,
                    length: { minimum: 5 }
end

blog/app/models/view.rb
class View < ActiveRecord::Base
  belongs_to :manga
end

blog/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

blog/app/controllers/mangas_controller.rb
class MangasController < ApplicationController
  def destroy
    @manga = Manga.find(params[:id])
    @manga.destroy

    redirect_to mangas_path
  end
  def update
    @manga = Manga.find(params[:id])

    if @manga.update(manga_params)
      redirect_to @manga
    else
      render 'edit'
    end
  end
  def edit
    @manga = Manga.find(params[:id])
  end
  def index
    @mangas = Manga.all
  end
  def show
    @manga = Manga.find(params[:id])
  end
  def new
    @manga = Manga.new
  end
  def create
    @manga = Manga.new(manga_params)

    if @manga.save
      redirect_to @manga
    else
      render 'new'
    end
  end
  private
  def manga_params
    params.require(:manga).permit(:title, :text)
  end
end

blog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def create
    @secondseason = Secondseason.find(params[:secondseason_id])
    @post = @secondseason.posts.create(post_params)
    redirect_to secondseason_path(@secondseason)
  end

  def destroy
    @secondseason = Secondseason.find(params[:secondseason_id])
    @post = @secondseason.posts.find(params[:id])
    @post.destroy
    redirect_to secondseason_path(@secondseason)
  end

  private
    def post_params
      params.require(:post).permit(:commenter, :body)
    end
end

blog/app/controllers/views_controller.rb
class ViewsController < ApplicationController
  def create
    @manga = Manga.find(params[:manga_id])
    @view = @manga.views.create(view_params)
    redirect_to manga_path(@manga)
  end

  def destroy
    @manga = Manga.find(params[:manga_id])
    @view = @manga.views.find(params[:id])
    @view.destroy
    redirect_to manga_path(@manga)
  end

  private
    def view_params
      params.require(:view).permit(:commenter, :body)
    end
end

blog/app/helpers/anime_helper.rb
module AnimeHelper
end

blog/app/helpers/animes_helper.rb
module AnimesHelper
end

blog/app/helpers/application_helper.rb
module ApplicationHelper
end

blog/app/helpers/chapters_helper.rb
module ChaptersHelper
end

blog/app/helpers/comments_helper.rb
module CommentsHelper
end

blog/app/helpers/episodes_helper.rb
module EpisodesHelper
end

blog/app/helpers/home_helper.rb
module HomeHelper
end

blog/app/helpers/mangas_helper.rb
module MangasHelper
end

blog/app/helpers/posts_helper.rb
module PostsHelper
end

blog/app/helpers/secondseasons_helper.rb
module SecondseasonsHelper
end

blog/app/helpers/views_helper.rb
module ViewsHelper
end

blog/app/views/mangas/_form.html.erb
<%= form_for @manga do |f| %>
  <% if @manga.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@manga.errors.count, "error") %> prohibited
      this manga from being saved:</h2>
    <ul>
    <% @manga.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

blog/app/views/mangas/edit.html.erb
<h1>Editing manga</h1>

<%= render 'form' %>

<%= link_to 'Back', mangas_path %>

blog/app/views/mangas/index.html.erb
<h1>Listing mangas</h1>

<%= link_to 'New manga', new_manga_path %>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="3"></th>
  </tr>

<% @mangas.each do |manga| %>
  <tr>
    <td><%= manga.title %></td>
    <td><%= manga.text %></td>
    <td><%= link_to 'Show', manga_path(manga) %></td>
    <td><%= link_to 'Edit', edit_manga_path(manga) %></td>
    <td><%= link_to 'Destroy', manga_path(manga),
                    method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<%= link_to 'New manga', new_manga_path %>

blog/app/views/mangas/new.html.erb
<h1>New manga</h1>

<%= render 'form' %>

<%= link_to 'Back', mangas_path %>

blog/app/views/mangas/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @manga.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @manga.text %>
</p>

<h2>Comments</h2>
<%= render @manga.chapters %>

<h2>Add a comment:</h2>
<%= render "chapters/form" %>

<h2>Comments</h2>
<%= render @manga.views %>

<h2>Add a comment:</h2>
<%= render "views/form" %>

<%= link_to 'Back', mangas_path %>
| <%= link_to 'Edit', edit_manga_path(@manga) %>